---
production:
  - name: "203.0.113.1"
    role: "hub"
    username: "admin"
    password: "admin"
  - name: "203.0.113.12"
    role: "spoke"
    username: "cisco"
    password: "cisco"
  - name: "203.0.113.11"
    role: "spoke"
    username: "cisco"
    password: "cisco"
...
